name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Depedencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: |
          git config --global usar.name "Diego Ruvalcaba"
          git config --global user.email "diego.ruvalcaba11@gmail.com"
          git add .
          git commit -m "Modified Feed"
          git push
